server:
    port: 8081

spring:
  application:
    name: spring-boot-ai-mcp-client
    
  ai:
    openai:
      api-key: ignored
      base-url: http://localhost:12434/engines
      chat:
        options:
          model: ai/gemma3
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            mongo-mcp-server:
              url: http://localhost:8080
          #stdio:
          # servers-configuration: classpath:mcp-servers-config.json
#        stdio:
#          connections:
#            -mcp-server:
#              command: java
#              args:
#                - "-jar"
#                - "<path-to-mcp-server-jar-file>"
#              env:
#                "HOST": "localhost"
#                "PORT": "27017"